#!/bin/bash

# GET CURRENT BUILD
version=`cat version.txt`
IFS='.' read verhi verlo build release <<< "$version"
[ $verhi == "" ] && verhi=0
[ $verlo == "" ] && verlo=0
[ $build == "" ] && build=0
[ $release == "" ] && release=dev

# INCREMENT BUILD VERSION
[ $# -eq 1 ] && [ $1 = "-i" ] && build=$(( $build + 1 ))
version=$verhi.$verlo.$build.$release

# UPDATE BUILD
rm v*.ver
echo $version>version.txt
echo v$version>v$version.ver

# TEST-RUN
./venv/bin/python3 netadmin_api_server.py $@
