#!/bin/bash

if [ -z "$2" ]; then
    echo "Syntax: $0 <device> <token>"
    exit 1
fi

curl -H 'Accept: application/json' -H "Authorization: Bearer $2" -X GET "http://127.0.0.1:4010/netadmin/nodes/$1"
echo

